### ISSUE TITLE
Need guide to start

### ISSUE THREAD

**Issue by Zhihaotan** [raviMukti/shopee-api-client#12]
Hi,

Really appreciate for your sharing

I've been trying to understand how this work for days, after setted .env with Dotenv, how can I get SHOPEE_ACCESS_TOKEN?

Sorry, I've limited PHP knowledge, but I need to do this, as Shopee API v1 is going to turn off, I used to intergrade v1 in my system, but v2 has this token issue, still figuring it out.

Thanks in advance for the help

**Comment by raviMukti** [comment]
Hello,

You will get the access token after you succeed authorize shop, let me explain in step by step
1. Go to authorize shop with this API [/api/v2/shop/auth_partner](https://partner.shopeemobile.com/api/v2/shop/auth_partner)
2. After you login using seller/store account, then it will redirect and you will get shop_id and auth_code in the URI
3. Next you'll need to get the access token via this API [/api/v2/auth/token/get](https://partner.shopeemobile.com/api/v1/shop/auth_partner) . Here is my example of doing this :
```
        $shopeeClient = new GeneralApiClient();
        $apiConfig = new ShopeeApiConfig();
        $apiConfig->setPartnerId($_ENV["SHOPEE_PARTNER_ID"]);
        $apiConfig->setSecretKey($_ENV["SHOPEE_SECRET_KEY"]);

        $baseUrl = "https://partner.test-stable.shopeemobile.com";
        $apiPath = "/api/v2/auth/token/get";

        $params = array();

        $body = array(
            "partner_id" => (int) $_ENV["SHOPEE_PARTNER_ID"],
            "code" => $_ENV["SHOPEE_CODE"],
            "shop_id" => (int) $_ENV["SHOPEE_SHOP_ID"]
        );

        $accessToken = $shopeeClient->httpCallPost($baseUrl, $apiPath, $params, $body, $apiConfig);

        $this->assertIsString($accessToken->access_token, "CREATE ACCESS TOKEN");
```

I think that's enough, let me know if it still doesn't work, hope it helps

**Comment by Zhihaotan** [comment]
Yay~ It is working now, THANKS!

Now may need to study refresh token & update token things? (waiting for it to expire)
Will continue to study /tests/node/general/GeneralWithBodyRequestTest.php

**Comment by raviMukti** [comment]
Honestly, you can try to refresh token without waiting for it to expire
